name:                singleton-list-question
version:             0.1.0.0
license:             BSD3
author:              "Callum Rogers"
maintainer:          "message.me@github.com"
copyright:           "Callum Rogers 2017"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         None

dependencies:
- base >= 4.7 && < 5
- singletons

library:
  source-dirs: src
